# Generated by Django 3.1.1 on 2020-09-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='type', max_length=15, unique=True)),
                ('maximumSize', models.IntegerField(db_column='maximum_size')),
            ],
            options={
                'db_table': 'file_type',
            },
        ),
        migrations.CreateModel(
            name='MimeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='type', max_length=150, unique=True)),
                ('fileType', models.ForeignKey(db_column='file_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='mimeFileType', to='asset.filetype')),
            ],
            options={
                'db_table': 'mime_type',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(db_column='file_name', max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('fileType', models.ForeignKey(db_column='file_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aasetFileType', to='asset.filetype')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
    ]
